kurento:
  __name: KURENTO
  __format: json

redisHost: REDIS_HOST
redisPort: REDIS_PORT
redisPassword: REDIS_PASSWORD

mcs-port: MCS_PORT
mcs-address: MCS_HOST

freeswitch:
    ip: FREESWITCH_CONN_IP
    sip_ip: FREESWITCH_SIP_IP
    port: FREESWITCH_SIP_PORT
    esl_ip: ESL_IP
    esl_port: ESL_PORT
    handleExternalConnections: FS_HANDLE_EXT_CONN

log:
    level: LOG_LEVEL
    filename: LOG_FILENAME
    maxFiles: LOG_MAX_FILES

bbb-stream:
  image_name: STREAM_IMAGE_NAME
  bigbluebutton_url: STREAM_BIGBLUEBUTTON_URL
  bigbluebutton_secret: STREAM_BIGBLUEBUTTON_SECRET
  container_type: STREAM_CONTAINER_TYPE
  bot_name: STREAM_BOT_NAME
  bot_join_options:
    __name: BOT_JOIN_OPTS
    __format: json

rnp:
  oauth2:
    client_id: VIDEO_RNP_CLIENT_ID
    client_secret: VIDEO_RNP_CLIENT_SECRET
    redirect_uri: VIDEO_RNP_REDIRECT_URI
    host_ip: VIDEO_RNP_HOST_IP
    base_url: VIDEO_RNP_BASE_URL

recordWebcams: RECORD_WEBCAMS
recordScreenSharing: RECORD_SCREENSHARE
recordingMediaProfile: RECORDING_MEDIA_PROFILE
recordingFormat: RECORDING_FORMAT

processes:
  __name: SFU_PROCESSES
  __format: json

conference-media-specs:
  codec_video_main: CODEC_VIDEO_MAIN
  codec_video_main_priority: CODEC_VIDEO_MAIN_PRIO
  codec_video_content: CODEC_VIDEO_CONTENT
  codec_video_content_priority: CODEC_VIDEO_CONTENT_PRIO

videoSubscriberSpecSlave: VIDEO_SUBSCRIBER_SLAVE
screenshareSubscriberSpecSlave: SCREENSHARE_SUBSCRIBER_SLAVE

kurentoAllowedCandidateIps:
  __name: KURENTO_ALLOWED_CANDIDATE_IPS
  __format: json

addTimestampToAkkaMessages: AKKA_MSG_TIMESTAMP
